import PageLayout from '../components/landing/PageLayout';

const UserAgreementPage = () => {
    return (
        <PageLayout>
            <div className="bg-white py-16">
                <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                    <h1 className="text-4xl font-extrabold text-gray-900 mb-8">User Agreement</h1>
                    <div className="prose prose-lg text-gray-600">
                        <p className="mb-6">
                            By using Dhitantra, you agree to the following:
                        </p>

                        <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">1. Fair Usage</h2>
                        <p className="mb-6">You will use the platform for learning purposes only and will not misuse or exploit the system.</p>

                        <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">2. Academic Integrity</h2>
                        <p className="mb-6">You will not engage in cheating, impersonation, or unfair practices during tests.</p>

                        <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">3. Acceptance of Results</h2>
                        <p className="mb-6">All scores, rankings, and results generated by the platform are final.</p>

                        <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">4. Content Usage</h2>
                        <p className="mb-6">You will not copy or distribute test content without authorization.</p>

                        <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">5. Compliance</h2>
                        <p className="mb-6">You agree to comply with all applicable laws and platform policies.</p>

                        <p className="mb-6 font-semibold">Violation of this agreement may result in account suspension or termination.</p>
                    </div>
                </div>
            </div>
        </PageLayout>
    );
};

export default UserAgreementPage;
